PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- Global product settings (edited in the Settings UI). Secrets stay in .env.
CREATE TABLE IF NOT EXISTS app_settings (
  id                         INTEGER PRIMARY KEY CHECK (id = 1),
  blocked_countries          TEXT NOT NULL DEFAULT '',
  block_freemail             INTEGER NOT NULL DEFAULT 1,
  brand_logo_url             TEXT NOT NULL DEFAULT '',
  brand_product_url          TEXT NOT NULL DEFAULT 'https://getobserver.app',
  brand_primary_color        TEXT NOT NULL DEFAULT '#6ea8fe',
  daily_send_cap             INTEGER NOT NULL DEFAULT 30,
  min_minutes_between_sends  INTEGER NOT NULL DEFAULT 1,
  send_window_start_hour     INTEGER NOT NULL DEFAULT 9,
  send_window_end_hour       INTEGER NOT NULL DEFAULT 22,
  send_window_timezone       TEXT NOT NULL DEFAULT 'Asia/Kolkata',
  send_on_weekends           INTEGER NOT NULL DEFAULT 1,
  include_unsubscribe_link   INTEGER NOT NULL DEFAULT 1,
  unsubscribe_base_url       TEXT NOT NULL DEFAULT 'http://localhost:8787',
  localize_emails            INTEGER NOT NULL DEFAULT 1,
  target_markets             TEXT NOT NULL DEFAULT '',
  target_company_signals     TEXT NOT NULL DEFAULT '',
  max_contacts_per_company   INTEGER NOT NULL DEFAULT 10,
  crawl_max_pages            INTEGER NOT NULL DEFAULT 15,
  updated_at                 TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS projects (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  name         TEXT NOT NULL,
  domain       TEXT NOT NULL UNIQUE,
  workflow_type TEXT NOT NULL DEFAULT 'customer_outreach',
  workflow_data TEXT NOT NULL DEFAULT '{}',
  -- html = multipart with branded HTML wrapper; plain = text-only (often better for cold mail)
  email_format TEXT NOT NULL DEFAULT 'html',
  created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

-- What the crawler + LLM understood about the product being sold.
CREATE TABLE IF NOT EXISTS site_profiles (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id   INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  pages_json   TEXT NOT NULL,
  analysis     TEXT,
  created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

-- An ICP / target audience. Generated by the LLM, then freely editable.
CREATE TABLE IF NOT EXISTS audiences (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id     INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name           TEXT NOT NULL,
  description    TEXT NOT NULL DEFAULT '',
  -- Roles the candidate wants (job_outreach). Empty for customer/investor ICPs.
  target_roles   TEXT NOT NULL DEFAULT '[]',
  -- People to contact: buyers (customer), investors, or hiring contacts (jobs).
  job_titles     TEXT NOT NULL DEFAULT '[]',
  industries     TEXT NOT NULL DEFAULT '[]',
  company_sizes  TEXT NOT NULL DEFAULT '[]',
  -- Adapter ids: yc, techstars, 500global, antler, ef, surge, producthunt, web.
  -- Empty = auto-select from campaign company signals.
  source_adapters TEXT NOT NULL DEFAULT '[]',
  -- Keep companies with batch/launch year >= this (0 = no filter).
  funded_after_year INTEGER NOT NULL DEFAULT 0,
  search_queries TEXT NOT NULL DEFAULT '[]',
  pain_points    TEXT NOT NULL DEFAULT '[]',
  value_prop     TEXT NOT NULL DEFAULT '',
  template_subject TEXT NOT NULL DEFAULT '',
  template_body    TEXT NOT NULL DEFAULT '',
  -- Optional custom HTML for this audience. Empty = auto-wrap plain template_body.
  template_html    TEXT NOT NULL DEFAULT '',
  next_search_page INTEGER NOT NULL DEFAULT 1,
  origin         TEXT NOT NULL DEFAULT 'generated',
  enabled        INTEGER NOT NULL DEFAULT 1,
  created_at     TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at     TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS companies (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id   INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  audience_id  INTEGER NOT NULL REFERENCES audiences(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  domain       TEXT NOT NULL,
  description  TEXT NOT NULL DEFAULT '',
  size_hint    TEXT NOT NULL DEFAULT '',
  country      TEXT NOT NULL DEFAULT '',
  source_url   TEXT NOT NULL DEFAULT '',
  created_at   TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (project_id, audience_id, domain)
);

CREATE TABLE IF NOT EXISTS contacts (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id       INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  audience_id      INTEGER NOT NULL REFERENCES audiences(id) ON DELETE CASCADE,
  company_id       INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  full_name        TEXT NOT NULL DEFAULT '',
  title            TEXT NOT NULL DEFAULT '',
  email            TEXT NOT NULL,
  -- How we got the address: scraped | pattern | manual | imported
  email_source     TEXT NOT NULL DEFAULT 'pattern',
  -- Where a human could go to see why this person is a reasonable contact.
  -- Required to defend a GDPR legitimate-interest position.
  evidence_url     TEXT NOT NULL DEFAULT '',
  country          TEXT NOT NULL DEFAULT '',
  verify_status    TEXT NOT NULL DEFAULT 'unverified',
  verify_score     INTEGER,
  created_at       TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (project_id, email)
);

CREATE TABLE IF NOT EXISTS messages (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id          INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  contact_id          INTEGER NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  audience_id         INTEGER NOT NULL REFERENCES audiences(id) ON DELETE CASCADE,
  subject             TEXT NOT NULL,
  body                TEXT NOT NULL,
  -- Optional custom HTML. Empty = auto-wrap plain body with branded footer.
  html_body           TEXT NOT NULL DEFAULT '',
  email_format        TEXT NOT NULL DEFAULT '',
  sent_text_body      TEXT NOT NULL DEFAULT '',
  sent_html_body      TEXT NOT NULL DEFAULT '',
  -- draft | approved | sending | sent | failed | skipped
  status              TEXT NOT NULL DEFAULT 'draft',
  model               TEXT NOT NULL DEFAULT '',
  personalisation     TEXT NOT NULL DEFAULT '',
  unsubscribe_token   TEXT NOT NULL,
  provider_message_id TEXT,
  error               TEXT,
  approved_at         TEXT,
  sent_at             TEXT,
  created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Never contacted again, for any reason. Checked immediately before send.
CREATE TABLE IF NOT EXISTS suppressions (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id   INTEGER REFERENCES projects(id) ON DELETE CASCADE,
  email        TEXT,
  domain       TEXT,
  reason       TEXT NOT NULL DEFAULT 'manual',
  created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

-- One row per unit of work. Every stage is independently retryable, so a
-- provider outage costs you one stage rather than the whole run.
CREATE TABLE IF NOT EXISTS jobs (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id   INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  stage        TEXT NOT NULL,
  payload      TEXT NOT NULL DEFAULT '{}',
  status       TEXT NOT NULL DEFAULT 'pending',
  attempts     INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 3,
  last_error   TEXT,
  -- When set, a failed job is hidden from Needs attention / Setup / Audiences
  -- prompts. The job_failed activity log entry is kept.
  dismissed_at TEXT,
  run_after    TEXT NOT NULL DEFAULT (datetime('now')),
  created_at   TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Append-only audit trail: which provider was called, what it cost, what
-- happened to each message. This is the log you need when a domain starts
-- misbehaving and you have to work out why.
CREATE TABLE IF NOT EXISTS events (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id   INTEGER,
  kind         TEXT NOT NULL,
  ref          TEXT NOT NULL DEFAULT '',
  data         TEXT NOT NULL DEFAULT '{}',
  cost_usd     REAL NOT NULL DEFAULT 0,
  created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Learned work-email formats per company domain (global across projects).
-- Ranked by hit_count; discovery probes the top 2 before the default order.
CREATE TABLE IF NOT EXISTS domain_email_patterns (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  domain       TEXT NOT NULL,
  pattern_key  TEXT NOT NULL,
  hit_count    INTEGER NOT NULL DEFAULT 1,
  last_seen_at TEXT NOT NULL DEFAULT (datetime('now')),
  created_at   TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (domain, pattern_key)
);

-- Catch-all / credit-protection memory for email verification.
-- is_catch_all flips only after risky_streak consecutive people had ALL pattern
-- guesses return risky (see CATCH_ALL_PERSON_THRESHOLD). A single risky address
-- never short-circuits the remaining patterns for that person.
CREATE TABLE IF NOT EXISTS domain_verify_state (
  domain         TEXT PRIMARY KEY,
  is_catch_all   INTEGER NOT NULL DEFAULT 0,
  risky_streak   INTEGER NOT NULL DEFAULT 0,
  valid_hits     INTEGER NOT NULL DEFAULT 0,
  last_status    TEXT NOT NULL DEFAULT '',
  updated_at     TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_jobs_queue ON jobs (status, run_after);
CREATE INDEX IF NOT EXISTS idx_companies_audience ON companies (audience_id);
CREATE INDEX IF NOT EXISTS idx_contacts_audience ON contacts (audience_id);
CREATE INDEX IF NOT EXISTS idx_contacts_company ON contacts (company_id);
CREATE INDEX IF NOT EXISTS idx_messages_status ON messages (project_id, status);
CREATE INDEX IF NOT EXISTS idx_messages_token ON messages (unsubscribe_token);
CREATE INDEX IF NOT EXISTS idx_events_project ON events (project_id, created_at);
CREATE INDEX IF NOT EXISTS idx_domain_email_patterns_domain
  ON domain_email_patterns (domain, hit_count DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_suppressions_email ON suppressions (email)
  WHERE email IS NOT NULL;
