/** Mirrors server DEFAULT_MARKETS / DEFAULT_SIGNALS for new-campaign prefills. */
export const CUSTOMER_DEFAULT_MARKETS = [
  "United States",
  "Canada",
  "United Kingdom",
  "Ireland",
  "Australia",
  "New Zealand",
  "Germany",
  "Netherlands",
  "Switzerland",
  "Sweden",
  "Denmark",
  "Norway",
  "Finland",
  "Singapore",
  "UAE",
  "France",
  "Belgium",
  "Austria",
  "Spain",
  "Portugal",
  "Italy",
  "Latin America",
];

export const CUSTOMER_DEFAULT_SIGNALS = [
  "Recently funded",
  "Pre-Seed",
  "Seed",
  "Series A",
  "Series B",
  "YC",
  "Techstars",
  "500 Global",
  "Antler",
  "EF",
  "Surge",
  "accelerator-backed",
  "Bootstrapped",
  "Fast-growing AI",
  "B2B SaaS",
  "Developer Tools",
  "Design",
  "Sales Tech",
  "Recruiting",
  "Customer Success",
  "Product Management",
  "Security",
  "Infrastructure",
  "Hiring",
  "Remote-first",
  "Hybrid",
  "high meeting culture",
];
