<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { agentAPI, type AgentUserView } from '@/agent/api'
import Icon from '@/components/icons/Icon.vue'
const items = ref<AgentUserView[]>([]); const total = ref(0); const page = ref(1); const search = ref(''); const status = ref(''); const loading = ref(false); const error = ref(''); const pageSize = 20
let timer: ReturnType<typeof setTimeout> | undefined
const formatTime = (value: string) => value ? new Date(value).toLocaleString('zh-CN') : '—'
async function load() { loading.value = true; error.value = ''; try { const result = await agentAPI.adminUsers.list(page.value, pageSize, search.value.trim(), status.value); items.value = result.items; total.value = result.total } catch { error.value = '用户列表加载失败，请稍后重试。' } finally { loading.value = false } }
watch([search, status], () => { page.value = 1; if (timer) clearTimeout(timer); timer = setTimeout(() => void load(), 250) })
onMounted(() => void load())
</script>
<template><div class="space-y-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-2xl font-bold text-gray-900 dark:text-white">用户管理</h2><p class="mt-1 text-sm text-gray-500 dark:text-dark-400">查看通过本站注册并归属到当前站点的用户，共 {{ total }} 人。</p></div><button class="btn btn-secondary" :disabled="loading" @click="load"><Icon name="refresh" size="sm" class="mr-2" :class="{ 'animate-spin': loading }" />刷新</button></div><section class="card"><div class="grid gap-3 border-b border-gray-100 pb-4 dark:border-dark-700 sm:grid-cols-[1fr_180px]"><input v-model="search" class="input" type="search" placeholder="搜索用户 ID、邮箱或名称"><select v-model="status" class="input"><option value="">全部状态</option><option value="active">正常</option><option value="suspended">已停用</option></select></div><p v-if="error" role="alert" class="mt-4 text-sm text-red-600">{{ error }}</p><div class="mt-4 overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="text-xs uppercase tracking-wide text-gray-400"><tr><th class="px-3 py-3">用户</th><th class="px-3 py-3">用户 ID</th><th class="px-3 py-3">状态</th><th class="px-3 py-3">注册时间</th><th class="px-3 py-3">最近更新</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-dark-700"><tr v-for="user in items" :key="user.main_user_id"><td class="px-3 py-4"><p class="font-medium text-gray-900 dark:text-white">{{ user.display_name || '未设置名称' }}</p><p class="mt-1 text-xs text-gray-500">{{ user.email || '未提供邮箱' }}</p></td><td class="px-3 py-4 font-mono text-xs">{{ user.main_user_id }}</td><td class="px-3 py-4">{{ user.status === 'active' ? '正常' : '已停用' }}</td><td class="px-3 py-4 text-gray-500">{{ formatTime(user.created_at) }}</td><td class="px-3 py-4 text-gray-500">{{ formatTime(user.updated_at) }}</td></tr><tr v-if="!loading && !items.length"><td colspan="5" class="px-3 py-12 text-center text-gray-500">暂无符合条件的用户</td></tr></tbody></table></div><div class="mt-4 flex justify-between border-t border-gray-100 pt-4"><span class="text-sm text-gray-500">第 {{ page }} 页</span><div class="flex gap-2"><button class="btn btn-secondary btn-sm" :disabled="page <= 1 || loading" @click="page--; load()">上一页</button><button class="btn btn-secondary btn-sm" :disabled="page * pageSize >= total || loading" @click="page++; load()">下一页</button></div></div></section></div></template>
