import { mount, flushPromises } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import AgentUserKeys from './AgentUserKeys.vue'
import AgentConfirmDialog from './AgentConfirmDialog.vue'
const keys = vi.hoisted(() => ({ listForUser: vi.fn(), createForUser: vi.fn(), revokeForUser: vi.fn() }))
vi.mock('@/agent/api', () => ({ agentAPI: { keys } }))
describe('AgentUserKeys', () => {
  beforeEach(() => vi.clearAllMocks())
  it('ignores stale creation after switching away and back, without unlocking a newer request', async () => {
    keys.listForUser.mockResolvedValue({ items: [] })
    let finishOld!: (value: { key: string }) => void
    let finishNew!: (value: { key: string }) => void
    keys.createForUser
      .mockImplementationOnce(() => new Promise(resolve => { finishOld = resolve }))
      .mockImplementationOnce(() => new Promise(resolve => { finishNew = resolve }))
    const wrapper = mount(AgentUserKeys, { props: { userId: '43' } })
    await flushPromises()
    await wrapper.get('form').trigger('submit')
    await wrapper.get('form').trigger('submit')
    expect(keys.createForUser).toHaveBeenCalledTimes(1)
    await wrapper.setProps({ userId: '44' })
    await wrapper.setProps({ userId: '43' })
    await flushPromises()
    await wrapper.get('form').trigger('submit')
    expect(keys.createForUser).toHaveBeenCalledTimes(2)
    finishOld({ key: 'stale-secret' })
    await flushPromises()
    expect(wrapper.text()).not.toContain('stale-secret')
    expect(wrapper.get('form button').attributes('disabled')).toBeDefined()
    finishNew({ key: 'current-secret' })
    await flushPromises()
    expect(wrapper.text()).toContain('current-secret')
    expect(wrapper.get('form button').attributes('disabled')).toBeUndefined()
    wrapper.unmount()
  })
  it('creates and revokes keys for the selected member, clearing secrets on user changes', async () => {
    keys.listForUser.mockResolvedValue({ items: [{ id: 7, name: 'client', prefix: 'agent', status: 'active' }] })
    keys.createForUser.mockResolvedValue({ key: 'one-time-secret' })
    keys.revokeForUser.mockResolvedValue({})
    const wrapper = mount(AgentUserKeys, { props: { userId: '43' } })
    await flushPromises()
    expect(wrapper.get('[data-status="active"]').text()).toBe('启用中')
    await wrapper.get('input').setValue('test client')
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(keys.createForUser).toHaveBeenCalledWith('43', 'test client')
    expect(wrapper.text()).toContain('one-time-secret')
    await wrapper.get('li button').trigger('click')
    await flushPromises()
    expect(keys.revokeForUser).not.toHaveBeenCalled()
    wrapper.getComponent(AgentConfirmDialog).vm.$emit('confirm')
    await flushPromises()
    expect(keys.revokeForUser).toHaveBeenCalledWith('43', 7)
    await wrapper.setProps({ userId: '44' })
    await flushPromises()
    expect(wrapper.text()).not.toContain('one-time-secret')
    expect(keys.listForUser).toHaveBeenLastCalledWith('44')
    wrapper.unmount()
  })
  it('cancels revocation and invalidates confirmation when the member changes', async () => {
    keys.listForUser.mockResolvedValue({ items: [{ id: 7, name: 'client', prefix: 'agent', status: 'active' }] })
    const wrapper = mount(AgentUserKeys, { props: { userId: '43' } })
    await flushPromises()
    await wrapper.get('li button').trigger('click')
    wrapper.getComponent(AgentConfirmDialog).vm.$emit('cancel')
    await flushPromises()
    expect(keys.revokeForUser).not.toHaveBeenCalled()
    await wrapper.get('li button').trigger('click')
    await wrapper.setProps({ userId: '44' })
    await flushPromises()
    expect(wrapper.getComponent(AgentConfirmDialog).props('open')).toBe(false)
    wrapper.getComponent(AgentConfirmDialog).vm.$emit('confirm')
    await flushPromises()
    expect(keys.revokeForUser).not.toHaveBeenCalled()
    wrapper.unmount()
  })
  it('does not show an old member revocation error on the newly selected member', async () => {
    keys.listForUser.mockResolvedValue({ items: [{ id: 7, name: 'client', prefix: 'agent', status: 'active' }] })
    let rejectRequest!: (reason: Error) => void
    keys.revokeForUser.mockImplementationOnce(() => new Promise((_resolve, reject) => { rejectRequest = reject }))
    const wrapper = mount(AgentUserKeys, { props: { userId: '43' } })
    await flushPromises()
    await wrapper.get('li button').trigger('click')
    wrapper.getComponent(AgentConfirmDialog).vm.$emit('confirm')
    await flushPromises()
    expect(keys.revokeForUser).toHaveBeenCalledWith('43', 7)
    await wrapper.setProps({ userId: '44' })
    await flushPromises()
    rejectRequest(new Error('previous member failed'))
    await flushPromises()
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
    expect(keys.listForUser).toHaveBeenLastCalledWith('44')
    wrapper.unmount()
  })
})
