server:
    host: 0.0.0.0
    port: 8080
    mode: debug
database:
    host: postgres
    port: 5432
    user: sub2api
    password: 1bc5eb56d7f83260bcc37f68b1ebf272bff3bdee80c5a925
    dbname: sub2api
    sslmode: disable
redis:
    host: redis
    port: 6379
    username: ""
    password: ""
    db: 0
    enable_tls: false
jwt:
    secret: 214397f389b6a1528355871caf472c76e71a9424c6e061412947408b56271753
    expire_hour: 24
default:
    user_concurrency: 5
    user_balance: 0
    api_key_prefix: sk-
    rate_multiplier: 1
rate_limit:
    requests_per_minute: 60
    burst_size: 10
timezone: Asia/Shanghai
